proyecto_vehiculos_django/proyecto_vehiculos_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehiculo.urls')),
]

proyecto_vehiculos_django/vehiculo/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('vehiculo/add/', views.vehiculo_add, name='vehiculo_add'),
    path('register/', views.register_user, name='register'),
    path('vehiculo/list/', views.vehiculo_list, name='vehiculo_list'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

proyecto_vehiculos_django/vehiculo/models.py
from django.db import models

class Vehiculo(models.Model):
    MARCAS = [
        ('Fiat', 'Fiat'),
        ('Chevrolet', 'Chevrolet'),
        ('Ford', 'Ford'),
        ('Toyota', 'Toyota'),
    ]
    CATEGORIAS = [
        ('Particular', 'Particular'),
        ('Transporte', 'Transporte'),
        ('Carga', 'Carga'),
    ]
    CONDICION_PRECIO_CHOICES = [
        ('bajo', 'Bajo'),
        ('medio', 'Medio'),
        ('alto', 'Alto'),
    ]
    marca = models.CharField(max_length=20, choices=MARCAS, default='Ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(
        max_length=20, choices=CATEGORIAS, default='Particular')
    precio = models.DecimalField(max_digits=10, decimal_places=1)
    condicion_precio = models.CharField(
        max_length=10,
        choices=CONDICION_PRECIO_CHOICES,
        default='bajo',
    )
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = [
            ("visualizar_catalogo", "Puede visualizar el catálogo de vehículos"),
        ]

    def __str__(self):
        return self.modelo

proyecto_vehiculos_django/vehiculo/forms.py
from django import forms
from .models import Vehiculo
from django.contrib.auth.models import User

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['marca', 'modelo', 'serial_carroceria', 'serial_motor', 'categoria', 'precio']

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']

proyecto_vehiculos_django/vehiculo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied
from .forms import VehiculoForm, RegistrationForm
from .models import Vehiculo

def inicio(request):
    return render(request, 'vehiculo/index.html')

@permission_required('vehiculo.add_vehiculo', raise_exception=True)
def vehiculo_add(request):
    if request.method == 'POST':
        form = VehiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('inicio')
    else:
        form = VehiculoForm()

    return render(request, 'vehiculo/vehiculo_form.html', {'form': form})

def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            # Asignar el permiso al usuario.
            permission = Permission.objects.get(codename='visualizar_catalogo')
            user.user_permissions.add(permission)
            
            return redirect('login')
    else:
        form = RegistrationForm()

    return render(request, 'registration/register.html', {'form': form})

@login_required
def vehiculo_list(request):
    vehiculos = Vehiculo.objects.all()

    for vehiculo in vehiculos:
        if vehiculo.precio <= 10000:
            vehiculo.condicion_precio = 'bajo'
        elif 10000 < vehiculo.precio <= 30000:
            vehiculo.condicion_precio = 'medio'
        else:
            vehiculo.condicion_precio = 'alto'
    return render(request, 'vehiculo/vehiculo_list.html', {'vehiculos': vehiculos})

proyecto_vehiculos_django/vehiculo/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="es">
  <head>
    {% bootstrap_css %}
    <title>{% block title %}{% endblock %}</title>
    <style>

    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Vehiculos</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Inicio</a>
            </li>
            {% if user.is_authenticated and user.is_staff %}

                <li class="nav-item">
                  <a class="nav-link nav-link-dark" href="/vehiculo/add">Agregar</a>
                </li>

            {% endif %}
            <li class="nav-item">
              <a class="nav-link nav-link-dark" href="/vehiculo/list">Listar</a>
            </li>
          </ul>
          {% if user.is_authenticated %}
          <div class="d-flex">
            <span class="navbar-text me-3">
              Hola, {{ user.username }}
            </span>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link nav-link-dark" href="/logout">Salir</a>
              </li>
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">{% block content %}{% endblock %}</div>

    {% bootstrap_javascript %}
  </body>
</html>

proyecto_vehiculos_django/vehiculo/templates/vehiculo/index.html
{% extends 'base.html' %}

{% block title %}
    Catálogo de Vehículos
{% endblock %}

{% block content %}
    <h1 class="text-center">Catálogo de Vehículos</h1>
{% endblock %}

proyecto_vehiculos_django/vehiculo/templates/vehiculo/vehiculo_form.html
{% extends 'base.html' %}

{% block title %}Añadir Vehículo{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>
{% endblock %}

proyecto_vehiculos_django/vehiculo/templates/vehiculo/vehiculo_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Listado de Vehículos</h2>
  <table class="table table-hover">
    <thead>
      <tr class="border-bottom">
        <th>Marca</th>
        <th>Modelo</th>
        <th>Serial Carrocería</th>
        <th>Serial Motor</th>
        <th>Categoría</th>
        <th>Precio</th>
        <th>Condición de Precio</th>
      </tr>
    </thead>
    {% for vehiculo in vehiculos %}
    <tr>
      <td>{{ vehiculo.marca }}</td>
      <td>{{ vehiculo.modelo }}</td>
      <td>{{ vehiculo.serial_carroceria }}</td>
      <td>{{ vehiculo.serial_motor }}</td>
      <td>{{ vehiculo.categoria }}</td>
      <td>{{ vehiculo.precio }}</td>
      <td>{{ vehiculo.get_condicion_precio_display }}</td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}